# This is a basic workflow to help you get started with Actions

name: parks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "parks" ]
  pull_request:
    branches: [ "parks" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: list
        run: echo "# National-Parks-Data-Analisys-Project" >> README.md
echo "# National-Parks-Data-Analisys-Project" >> README.md

git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/smycreates/National-Parks-Data-Analisys-Project.git
git push -u origin main

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |echo "# National-Parks-Data-Analisys-Project" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/smycreates/National-Parks-Data-Analisys-Project.git
git push -u origin main
          echo Add other actions to build,
          echo test, and deploy your project.
